// var nameList = [{name: '宋 治 佳', id: 'zhijia.song'}];
// 卓越
var zhuoyueNamelist = [
    { name: '万 瑞 阳', id: 'ruiyang.wan'},
    { name: '吉 坤', id: 'kun.ji'},
    { name: '张 俭', id: 'nostalie.zhang'},
    { name: '陈 美 霖', id: 'youthlin.chen'},
    { name: '刘 晓 倩', id: 'liuxiaoqian.liu'}
];
// 优秀
var youxiuNamelist = [
    { name: '芦 梦 宇', id: 'lumengyu.lu'},
    { name: '宋 治 佳', id: 'zhijia.song'},
    { name: '赵 一 迪', id: ',yidi.zhao'},
    { name: '蔚 将 将', id: 'jiangjiang.yu'},
    { name: '董 文 博', id: 'wenbo.dong'},
    { name: '田 琦', id: 'tianqi.tian'},
    { name: '郑 含', id: 'han.zheng'},
    { name: '周 桦', id: 'zhouhua.zhou'},
    { name: '郭 泽 川', id: 'zechuan.guo'},
    { name: '林 小 淞', id: 'xiaosong.lin'},
    { name: '袁 佳 露', id: 'jialu.yuan'},
    { name: '王 晖', id: 'wanghuiwh.wang'},
    { name: '张 宁', id: 'kingsley.zhang'},
    { name: '田 昆', id: 'tiankun.tian'},
    { name: '马 恺', id: 'kai.ma'},
    { name: '郭 泽 欣', id: 'zexin.guo'},
    { name: '郑 晨 辉', id: 'chenhui.zheng'},
    { name: '李 磊', id: 'leili.li'},
    { name: '王 高 俊', id: 'gaojun.wang'},
    { name: '靳 伟 迪', id: 'w,eidi.jin'},
    { name: '李 浩 川', id: 'haochuan.li'},
    { name: '朱 潇 翔', id: 'zhuxiaoxiang.zhu'},
    { name: '杜 健', id: 'jian.du'},
    { name: '申 浩 杰', id: 'haojie.shen'}
];
// 普通
var putongNamelist = [
    { name: '黄 巧 艳', id: 'qiaoyan.huang'},
    { name: '李 程 程', id: 'chch.li'},
    { name: '石 皓 洋', id: 'haoyang.shi'},
    { name: '郝 科', id: 'ke.hao'},
    { name: '杨 侨', id: 'qiaoy.yang'},
    { name: '冉 玉 凤', id: 'yufeng.ran'},
    { name: '王 志 敏', id: 'wangzhimin.wang'},
    { name: '郑 睿 杰', id: 'ruijie.zheng'},
    { name: '李 阳', id: 'sunshine.li'},
    { name: '易 方 铭', id: 'fangming.yi'},
    { name: '卢 彩 云', id: 'caiyun.lu'},
    { name: '吕 帅', id: 'shuai.lv'},
    { name: '沙 丹 丹', id: 'dandan.sha'},
    { name: '李 宁', id: 'llnn.li'},
    { name: '张 晓 洁', id: 'zhangxiaojie.zhang'},
    { name: '丁 杰', id: 'jie.ding'},
    { name: '林 钱 雷', id: 'qianlei.lin'},
    { name: '刘 爱 兰', id: 'ailan.liu'},
    { name: '王 显 宇', id: 'wangxianyu.wang'},
    { name: '刘 裕', id: 'lyliuyu.liu'},
    { name: '方 昆', id: 'fangkun.fang'},
    { name: '郭 崇 源', id: 'chongyuan.guo'},
    { name: '杨 润 雪', id: 'runxue.yang'},
    { name: '李 维 维', id: 'liweiwei.li'},
    { name: '孙 文 超', id: 'wenchao.sun'},
    { name: '李 洋', id: 'leeyang.li'},
    { name: '常 星 星', id: 'xingxing.chang'},
    { name: '刘 汶 波', id: 'wenbo.liu'},
    { name: '马 万 龙', id: 'wanlong.ma'},
    { name: '郝 瑞', id: 'ryan.hao'},
    { name: '温 勇 涛', id: 'yongtao.wen'},
    { name: '任 天 一', id: 'tianyi.ren'},
    { name: '王 蕾', id: 'wangleiwl.wang'},
    { name: '迟 善 琳', id: 'shanlin.chi'},
    { name: '杨 悦', id: 'yangyueyy.yang'},
    { name: '权 金 铎', id: 'jinduo.quan'},
    { name: '刘 小 丽', id: 'liuxiaoli.liu'},
    { name: '蔡 加 挺', id: 'jiating.cai'},
    { name: '徐 开 明', id: 'kaiming.xu'},
    { name: '赵 婧 如', id: 'jingru.zhao'},
    { name: '曹 卫 驹', id: 'weiju.cao'},
    { name: '刘 心 乔', id: 'xinqiao.liu'},
    { name: '王 建 明', id: 'jm.wang'},
    { name: '王 威', id: 'weiwang.wang'},
    { name: '祝 鑫 奔', id: 'xinben.zhu'},
    { name: '许 欣', id: 'xuxinxx.xu'},
    { name: '张 探 琛', id: 'tanchen.zhang'}
];